trigger:
  - master

pr:
  - master

jobs:
  - job: CodeCheck
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: NodeTool@0
        displayName: Install Node.js
        inputs:
          versionSpec: 12.x

      - script: npm install
        displayName: Install dependencies

      - script: npm run lint
        displayName: Lint

      - script: npm run typecheck
        displayName: Type Check

  - template: azure-pipelines-template.yml
    parameters:
      name: Firefox
      vmImage: 'ubuntu-latest'
      nodeVersion: '8.x'
      browser: 'firefox'
      headless: 'true'

  - template: azure-pipelines-template.yml
    parameters:
      name: Chrome
      vmImage: 'ubuntu-latest'
      nodeVersion: '12.x'
      browser: 'chrome'
      headless: 'true'
      preBuild:
        - script: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt update
            sudo apt install google-chrome-stable
          displayName: 'Install latest stable Chrome'

  # - template: azure-pipelines-template.yml
  #   parameters:
  #     name: Safari
  #     vmImage: 'macOS-latest'
  #     nodeVersion: '10.x'
  #     browser: 'safari'
  #     preBuild:
  #     - script: sudo safaridriver --enable
  #       displayName: Configure Safari to Enable WebDriver Support

  - template: azure-pipelines-template.yml
    parameters:
      name: Internet_Explorer
      vmImage: 'windows-latest'
      nodeVersion: '12.x'
      browser: 'internet-explorer'

  # - template: azure-pipelines-template.yml
  #   parameters:
  #     name: BrowserStack_Firefox
  #     vmImage: 'ubuntu-latest'
  #     nodeVersion: '12.x'
  #     browser: 'firefox'
  #     browserStack: 'true'

  - template: azure-pipelines-template.yml
    parameters:
      name: BrowserStack_Safari
      vmImage: 'ubuntu-latest'
      nodeVersion: '12.x'
      browser: 'safari'
      browserStack: 'true'
