name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Check code style
        run: npm run lint
      - name: Check types
        run: npm run typecheck
  test:
    needs: lint-typecheck
    strategy:
      fail-fast: false
      matrix:
        environment: [Firefox, Chrome, Internet_Explorer, BrowserStack_Safari]
        include:
          - environment: Firefox
            os: 'ubuntu-latest'
            nodeVersion: '8.x'
            browser: 'firefox'
            headless: 'true'
          - environment: Chrome
            os: 'ubuntu-latest'
            nodeVersion: '12.x'
            browser: 'chrome'
            headless: 'true'
          - environment: Internet_Explorer
            os: 'windows-latest'
            nodeVersion: '12.x'
            browser: 'internet-explorer'
          - environment: Safari
            os: 'macos-latest'
            nodeVersion: '12.x'
            browser: 'safari'
          # - environment: BrowserStack_Safari
          #   os: 'ubuntu-latest'
          #   nodeVersion: '12.x'
          #   browser: 'safari'
          #   browserStack: 'true'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: Install dependencies
        run: npm ci
        env:
          CHROMEDRIVER_VERSION: '79.0.3945.36'
      - name: Enable Safari Driver
        run: |
          mkdir -p ~/Library/WebDriver/
          curl https://raw.githubusercontent.com/web-platform-tests/wpt/master/tools/ci/azure/com.apple.Safari.plist -o ~/Library/WebDriver/com.apple.Safari.plist
          defaults write com.apple.Safari WebKitJavaScriptCanOpenWindowsAutomatically 1
          sudo safaridriver --enable
          safaridriver -p 0 &
        if: matrix.browser == 'safari'
      - name: Run tests
        run: npm run test:coverage
        env:
          BROWSER: ${{ matrix.browser }}
          HEADLESS: ${{ matrix.headless }}
          BROWSERSTACK: ${{ matrix.browserStack }}
          BROWSERSTACK_USERNAME: ${{ secrets.browserStackUsername }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.browserStackAccessKey }}
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.codeCovUploadToken }} #required
